name: dfc_store
description: DFC Store
version: 1.0.1
homepage: distantfutu.re
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.0
  dfc_flutter:
    git: https://github.com/sgehrman/dfc_flutter
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  http: ^1.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/JonasWanke/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.9.5

flutter: null
