name: dfc_store
description: DFC Store
version: 1.0.1
homepage: distantfutu.re
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.1
  dfc_flutter:
    git: https://github.com/sgehrman/dfc_flutter.git
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.7.1
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/JonasWanke/dart-code-metrics.git
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints.git
  json_serializable: ^6.11.1

flutter: null
